---
language: node_js
node_js:
  - '0.10'

before_script:
  - npm install -g phantomjs
  - cp protractor.conf.js.travis protractor.conf.js
  - cp karma.conf.js.travis karma.conf.js
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
